var school_data = [{
        "school_district": "Katy Independent School District",
        "address": "6301 South Stadium Lane",
        "city": "Katy",
        "state": "TX",
        "zip": "77494",
        "phone": "(281) 396-6000",
        "graduation_rate": "93.8%",
        "dropout_rate": "1.0%",
        "per_pupil_spending": "$7,607",
        "students_per_teacher": "14.5",
        "number_of_schools": "57",
        "number_of_students": "56,862",
        "number_of_teachers": "3,916"
    },
    {
        "school_district": "Fort Bend Independent School District",
        "address": "16431 Lexington Boulevard",
        "city": "Sugar Land",
        "state": "TX",
        "zip": "77479",
        "phone": "(281) 634-1000",
        "graduation_rate": "82.2%",
        "dropout_rate": "2.4%",
        "per_pupil_spending": "$7,636",
        "students_per_teacher": "15.8",
        "number_of_schools": "75",
        "number_of_students": "68,708",
        "number_of_teachers": "4,354"
    },
    {
        "school_district": "Cypress-Fairbanks Independent School District",
        "address": "10300 Jones Road",
        "city": "Houston",
        "state": "TX",
        "zip": "77065",
        "phone": "(281) 897-4000",
        "graduation_rate": "86.5%",
        "dropout_rate": "1.1%",
        "per_pupil_spending": "$7,138",
        "students_per_teacher": "15.7",
        "number_of_schools": "82",
        "number_of_students": "100,685",
        "number_of_teachers": "6,411"
    },
    {
        "school_district": "Conroe Independent School District",
        "address": "3205 West Davis",
        "city": "Conroe",
        "state": "TX",
        "zip": "77304",
        "phone": "(936) 709-7702",
        "graduation_rate": "84.1%",
        "dropout_rate": "0.7%",
        "per_pupil_spending": "$7,096",
        "students_per_teacher": "15.6",
        "number_of_schools": "59",
        "number_of_students": "47,996",
        "number_of_teachers": "3,082"
    },
    {
        "school_district": "Humble Independent School District",
        "address": "20200 Eastway Village Drive",
        "city": "Humble",
        "state": "TX",
        "zip": "77347",
        "phone": "(281) 641-1000",
        "graduation_rate": "86.6%",
        "dropout_rate": "3.5%",
        "per_pupil_spending": "$7,459",
        "students_per_teacher": "14.8",
        "number_of_schools": "42",
        "number_of_students": "33,883",
        "number_of_teachers": "2,292"
    },
    {
        "school_district": "La Porte Independent School District",
        "address": "1002 San Jacinto Street",
        "city": "La Porte",
        "state": "TX",
        "zip": "77571",
        "phone": "(281) 604-7015",
        "graduation_rate": "84.4%",
        "dropout_rate": "2.1%",
        "per_pupil_spending": "$8,547",
        "students_per_teacher": "15.6",
        "number_of_schools": "14",
        "number_of_students": "7,914",
        "number_of_teachers": "508"
    },
    {
        "school_district": "Clear Creek Independent School District",
        "address": "2425 East Main Street",
        "city": "League City",
        "state": "TX",
        "zip": "77573",
        "phone": "(281) 284-0079",
        "graduation_rate": "81.5%",
        "dropout_rate": "1.3%",
        "per_pupil_spending": "$7,586",
        "students_per_teacher": "15.5",
        "number_of_schools": "46",
        "number_of_students": "37,194",
        "number_of_teachers": "2,401"
    },
    {
        "school_district": "Pearland Independent School District",
        "address": "2337 North Galveston Avenue",
        "city": "Pearland",
        "state": "TX",
        "zip": "77581",
        "phone": "(281) 485-3203",
        "graduation_rate": "93.8%",
        "dropout_rate": "1.6%",
        "per_pupil_spending": "$6,917",
        "students_per_teacher": "16.3",
        "number_of_schools": "26",
        "number_of_students": "17,640",
        "number_of_teachers": "1,079"
    },
    {
        "school_district": "Houston Independent School District",
        "address": "4400 West 18th Street",
        "city": "Houston",
        "state": "TX",
        "zip": "77092",
        "phone": "(713) 556-6000",
        "graduation_rate": "56.6%",
        "dropout_rate": "6.8%",
        "per_pupil_spending": "$8,604",
        "students_per_teacher": "16.7",
        "number_of_schools": "309",
        "number_of_students": "200,225",
        "number_of_teachers": "11,994"
    },
    {
        "school_district": "Houston Independent School District",
        "address": "4400 West 18th Street",
        "city": "Houston",
        "state": "TX",
        "zip": "77092",
        "phone": "(713) 556-6000",
        "graduation_rate": "56.6%",
        "dropout_rate": "6.8%",
        "per_pupil_spending": "$8,604",
        "students_per_teacher": "16.7",
        "number_of_schools": "309",
        "number_of_students": "200,225",
        "number_of_teachers": "11,994"
    }
]

var state_avg = [{
    "graduation_rate": "73.1%",
    "dropout_rate": "4.0%",
    "per_pupil_spending": "$8,501",
    "students_per_teacher": "14.5"
}]